# Generated by Django 3.0 on 2021-02-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
