# Generated by Django 3.0 on 2021-02-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
